### ISSUE TITLE
Start/Stop not working by me

### ISSUE THREAD

**Issue by terslowe** [deblockt/hass-proscenic-790T-vacuum#1]
Hello,

By me the information is working such as Battery info, information to getting dock etc. but i can't start/stop/pauze the Robotic using Lovelace. Do you have any idea whats gooing wrong?

**Comment by stjones-dev** [comment]
For me is the same, no commands possible only status. Also, the app doesn't allow me to be logged in elsewhere so it kicks me out.

**Comment by deblockt** [comment]
Can you try this new release: https://github.com/deblockt/hass-proscenic-790T-vacuum/releases/tag/0.0.2 ?
I added the `authCode` configuration. You can found the process to retrieve it here: https://github.com/deblockt/hass-proscenic-790T-vacuum#configuration

**Comment by terslowe** [comment]
With these new release problem is solved. Thank you for your effort, Robotic is now working very fine with start stop get to the home only the mapping is not working.
