### ISSUE TITLE
can not connect to vacuum

### ISSUE THREAD

**Issue by tobit6795** [deblockt/hass-proscenic-790T-vacuum#11]
![grafik](https://user-images.githubusercontent.com/31254099/94827470-c669bd00-0408-11eb-91a7-cd16494d70d8.png)

im wondering what the problem is...the vacuum was already connected, i got the status when it was driving to the dockingstation and the battery level btw
atm any possible action isnt working

**Comment by tobit6795** [comment]
sooo, i just found out, that my FW ist to "new" and it doesnt accept the local send commands....do you have an idea how to send start/stop etc. over the "api" ?

**Comment by tobit6795** [comment]
Hi again, i just found out that you were working on this 
[https://community.home-assistant.io/t/proscenic-790t-integration/82969/76](url)

i tested fix/vacuum_start branch, works perfect!

**Comment by deblockt** [comment]
hi @tobit6795 sorry for the late... 
Is your targetId not equals to the deviceId? 
I try to understand if your issue can be solved without use the proscenic cloud system.

**Comment by Gedankenspiegel** [comment]
Hi there, I have the same issue.

Got the status of docked/driving etc.
When trying to control the robot via homeassistant instead of the app, I also get the error in Browser.

Scanning the IP of the Robot shows no open Port.

Firmwares:
- mcu: 1.8.2614
- esp: 1.036
There seem no further updates available.

Capturing the Packets of the App only Show communication to the 47.91.67.181 on port 20008 an some other WAN IPs with Port 80 but no connection to the IP of the Robot itself.
And the targetID does not equal the deviceID.

**Comment by deblockt** [comment]
Hi @Gedankenspiegel ,

I will try to provide a cloud feature for this integration, maybe that will solve your issue. 
When you perform the packet capture, are you on the same  network than your vacuum ?
 Is your Home assistant installation on the same network than your vacuum ?

**Comment by Gedankenspiegel** [comment]
Yep, same Network, same SSID, all three Devices.

Thomas Deblock ***@***.***> schrieb am Fr., 25. März 2022,
20:42:

**Comment by deblockt** [comment]
@Gedankenspiegel can you try the version 0.0.9 ? 
I added a cloud configuration. You should remove the integration a re-add it on integration panel.

**Comment by Gedankenspiegel** [comment]
Hi @deblockt 
Installed it an it works via cloud.

In the setup dialog authentication token is required and in the paket capture there is "token": and "appKey":
"appKey": works for me. This is a bit confusing.

**Comment by deblockt** [comment]
It's a good news 🎉 

@Gedankenspiegel Authentication token should be token not appkey. 
If it's works with appkey, maybe that this information is useless. I will try to remove it.

**Comment by Gedankenspiegel** [comment]
Yeah, but local seems to be blocked - cloud works.

**Comment by deblockt** [comment]
It seem that your vacuum don't allow a local connection (port 8888 not opened). 

Maybe that it use another port. 

that's why I put in the doc "Note: Some vacuum don't support the local mode."

**Comment by deblockt** [comment]
Hi @tobit6795, happy to see that your issue is partially resolved. 
For now, to get the map, I have not found how to work with the cloud, so I use the local connection to get the map. So it can not work with your vacuum. #21
