### ISSUE TITLE
targetId

### ISSUE THREAD

**Issue by bGd270** [deblockt/hass-proscenic-790T-vacuum#12]
Hello, i’m using this integration for my Proscenic 811gb
I did everything I should and I could see my vacuum status, battery but couldn’t control it from HA, then I went into vacuum_proscenic.py and replaced “targetId” with my actual “targetId” 
Now, i can control my vacuum but I lost battery level. Any idea?

**Comment by deblockt** [comment]
I have already seen that I can lose the battery level from time to time with the 790T but I don't know why. On the other hand I can't analyze too much with the 811gb because I don't have one. 

Can you provide me with the target id, so that I can add it directly into the integration.

**Comment by deblockt** [comment]
Hi, Is your targetId different of the deviceId?

**Comment by deblockt** [comment]
You can try with the last version and the "cloud" configuration

**Comment by deblockt** [comment]
Closed due to inactivity
