### ISSUE TITLE
Proscenic Cocosmart 820T

### ISSUE THREAD

**Issue by pex81** [deblockt/hass-proscenic-790T-vacuum#18]
Hello, will it work with the Cocosmart 820T model?
I tried to find authcode and targetid but they don't come out.

**Comment by deblockt** [comment]
Hi, this integration don't support Cocosmart 820T model. 
If you send me some capture maybe that i can do something, but it will be hard. 
maybe that you can use https://github.com/lclem/hass-proscenic-800T-vacuum
