### ISSUE TITLE
Map issue

### ISSUE THREAD

**Issue by goodbyepavlyi** [deblockt/hass-proscenic-790T-vacuum#30]
When the integration tries to pull the map it results in an error.
The response from the cloud:
`  {
  "control": {
    "broadcast": "0",
    "targetId": "000000000000", // REDACTED
    "targetType": "1"
  },
  "value": {
    "adjoinRegion": "",
    "areaAdjoin": "",
    "blockSize": "10000",
    "centerPoint": "352,364",
    "chargerPos": "370,318",
    "cleanArea": "[]",
    "clearArea": "3",
    "clearModule": "9",
    "clearSign": "2022-10-29-22-32-26-5",
    "clearTime": "209",
    "deg": "87",
    "doTime": "610209",
    "emptyMap": "0",
    "forbiddenArea": "[]",
    "isMove": "0",
    "leftMaxPoint": "300,309",
    "map": "BQAxAAEAAQAcAHic7cExAQAAAMKg9U9tCj+gAAAAAIC3AROIAAECAAEAHAB4nO3BMQEAAADCoPVPbQo/oAAAAACAtwETiAABAwABABwAeJztwTEBAAAAwqD1T20KP6AAAAAAgLcBE4gAAQQAAQAcAHic7cExAQAAAMKg9U9tCj+gAAAAAIC3AROIAAEFAAEAHAB4nO3BMQEAAADCoPVPbQo/oAAAAACAtwETiAABBgABABwAeJztwTEBAAAAwqD1T20KP6AAAAAAgLcBE4gAAQcAAQAcAHic7cExAQAAAMKg9U9tCj+gAAAAAIC3AROIAAEIAAEAHAB4nO3BMQEAAADCoPVPbQo/oAAAAACAtwETiAABCQABABwAeJztwTEBAAAAwqD1T20KP6AAAAAAgLcBE4gAAQoAAQAcAHic7cExAQAAAMKg9U9tCj+gAAAAAIC3AROIAAELAAEAHAB4nO3BMQEAAADCoPVPbQo/oAAAAACAtwETiAABDAABABwAeJztwTEBAAAAwqD1T20KP6AAAAAAgLcBE4gAAQ0AAQAcAHic7cExAQAAAMKg9U9tCj+gAAAAAIC3AROIAAEOAAEAHAB4nO3BMQEAAADCoPVPbQo/oAAAAACAtwETiAABDwABABwAeJztwTEBAAAAwqD1T20KP6AAAAAAgLcBE4gAARAAAQAcAHic7cExAQAAAMKg9U9tCj+gAAAAAIC3AROIAAERAAQAHAB4nO3BMQEAAADCoPVPbQo/oAAAAACAtwETiAABEgAIABwAeJztwTEBAAAAwqD1T20KP6AAAAAAgLcBE4gAARMACQAcAHic7cExAQAAAMKg9U9tCj+gAAAAAIC3AROIAAEUAAEAHAB4nO3BMQEAAADCoPVPbQo/oAAAAACAtwETiAABFQABABwAeJztwTEBAAAAwqD1T20KP6AAAAAAgLcBE4gAARYAAQAcAHic7cExAQAAAMKg9U9tCj+gAAAAAIC3AROIAAEXAAEAHAB4nO3BMQEAAADCoPVPbQo/oAAAAACAtwETiAABGAAEABwAeJztwTEBAAAAwqD1T20KP6AAAAAAgLcBE4gAARkAOQDqAHic7dXREcMgCAZgzQTBDWT/ISsxURPFwLW5a3v8r/VrFZE6Z/nrwB6FwJQnhU9LSWB8UOAevUCxCCakAvRCfR9D4YWiJKBWoFC0qR/3j3MuYJS5yLWH1eWXJBDXI96KcBLDpW+LY1eztY2oX/t5Ebcu8bWrb5OFAlBp2GbgCaxqMa/+QIR6jCgj9dhR9mONEO6uK21kap0qlNdeReRuhwSMBbeZrZ+WXrC1PmaAXiyiXVE1ypzpDjoU7WQSXQKJVSfKchNfKKhNgDqQH1tnkV8JAkwG3UU0f7wiUeNNmDBhwoSJHxcvlKFaiRoAGwBIAHic7dLRDQAQEMBQIzgTYP8hzVAJOdH337+WIklvCF7gZOBiRqXFsDhZwOBKwU+MnF91GKS9JGcBg42iXXmXFpIkST9ZmBoH4hsAAQAcAHic7cExAQAAAMKg9U9tCj+gAAAAAIC3AROIAAEcAAEAHAB4nO3BMQEAAADCoPVPbQo/oAAAAACAtwETiAABHQABABwAeJztwTEBAAAAwqD1T20KP6AAAAAAgLcBE4gAAR4AAQAcAHic7cExAQAAAMKg9U9tCj+gAAAAAIC3AROIAAEfAAQAHAB4nO3BMQEAAADCoPVPbQo/oAAAAACAtwETiAABIAAuAGYAeJzt0UsKgDAMRdHEFZjuoO5/kYL1g5KKQaKTe0blwZ00IhstU08dxdMvqn1RuMHrwprcYtnWwg/8wqx0z+EWGi7amFzIEC7k76J9/qXQuwvayb7Gi+P9kIYLAAAAAACQbgYTHjH0IQABABwAeJztwTEBAAAAwqD1T20KP6AAAAAAgLcBE4gAASIAAQAcAHic7cExAQAAAMKg9U9tCj+gAAAAAIC3AROIAAEjAAEAHAB4nO3BMQEAAADCoPVPbQo/oAAAAACAtwETiAABJAABABwAeJztwTEBAAAAwqD1T20KP6AAAAAAgLcBE4gAASUAAQAcAHic7cExAQAAAMKg9U9tCj+gAAAAAIC3AROIAAEmAAQAHAB4nO3BMQEAAADCoPVPbQo/oAAAAACAtwETiAABJwAEABwAeJztwTEBAAAAwqD1T20KP6AAAAAAgLcBE4gAASgAAQAcAHic7cExAQAAAMKg9U9tCj+gAAAAAIC3AROIAAEpAAEAHAB4nO3BMQEAAADCoPVPbQo/oAAAAACAtwETiAABKgABABwAeJztwTEBAAAAwqD1T20KP6AAAAAAgLcBE4gAASsAAQAcAHic7cExAQAAAMKg9U9tCj+gAAAAAIC3AROIAAEsAAEAHAB4nO3BMQEAAADCoPVPbQo/oAAAAACAtwETiAABLQAEABwAeJztwTEBAAAAwqD1T20KP6AAAAAAgLcBE4gAAS4ABAAcAHic7cExAQAAAMKg9U9tCj+gAAAAAIC3AROIAAEvAAEAHAB4nO3BMQEAAADCoPVPbQo/oAAAAACAtwETiAABMAABABwAeJztwTEBAAAAwqD1T20KP6AAAAAAgLcBE4gAATEAAQAcAHic7cExAQAAAMKg9U9tCj+gAAAAAIC3AQ==",
    "mapHeight": "700",
    "mapSign": "1",
    "mapType": "-1",
    "mapWidth": "700",
    "mopForbiddenArea": "[]",
    "pointArea": {},
    "regionNames": "[]",
    "regionNum": "0",
    "result": "0",
    "rightMaxPoint": "404,419",
    "robotPos": "335,407",
    "track": "BAQDAIsApgFVAVcBVQFVAVYBUwFYAVMBWQFSAVsBUQFdAVEBXwFSAWEBUgFjAVIBZQFSAWcBUQFoAU8BaQFNAWoBTAFrAUkBawFHAWsBSAFrAUkBawFKAWsBSwFrAUwBawFNAWsBTgFrAU8BawFQAWsBUQFrAVIBawFUAWsBVQFrAVYBawFYAWsBWQFrAVoBawFbAWsBXQFrAV4BawFfAWsBYAFrAWIBawFjAWsBZAFrAWUBawFnAWsBaAFrAWkBawFqAWsBbAFrAW0BawFuAWsBbwFrAXABawFyAWsBcwFrAXQBawF1AWsBdgFrAXcBawF5AWsBegFrAXsBagF8AWkBfQFnAX0BZgF8AWUBewFlAXoBZQF4AWUBdwFlAXYBZQF1AWUBdAFlAXMBZQFyAWUBcQFlAW8BZQFuAWUBbAFlAWsBZQFqAWUBaQFlAWcBZQFmAWUBZQFlAWQBZQFjAWUBYQFlAWABZQFfAWUBXgFlAVwBZQFbAWUBWgFlAVkBZAFYAWMBVwFhAVcBYAFYAV8BWQFfAVoBXwFbAV8BXAFfAV0BXwFfAV8BYAFfAWEBXwFiAV8BYwFfAWUBXwFmAV8BZwFfAWgBXwFqAV8BawFfAWwBXwFtAV8BbwFfAXABXwFxAV8BcwFfAXQBXwF1AV8BdgFfAXgBXwF5AV8BegFfAXsBXwF9AV8BfgFfAX8BXwGAAV8BgQFeAYIBXQGDAVsBgwFaAYIBWQGBAVkBgAFZAX8BWQF+AVkBfQFZAXwBWQF7AVkBegFZAXkBWQF3AVkBdgFZAXUBWQF0AVkBcgFZAXEBWQFwAVkBbwFZAW0BWQFsAVkBawFZAWkBWQFoAVkBZwFZAWYBWQFkAVkBYwFZAWIBWQFgAVkBXwFZAV4BWQFcAVkBWwFZAVoBWQFZAVkBVwFYAVYBVgFWAVUBVwFWAVgBVgFaAVYBXAFWAV8BVQFhAVQBYgFTAWQBUwFlAVMBZgFTAWcBUwFoAVMBagFTAWsBUwFsAVMBbQFTAW8BUwFwAVMBcQFTAXMBUwF0AVMBdQFTAXYBUwF4AVMBeQFTAXoBUwF7AVMBfQFTAX4BUwF/AVMBgAFTAYEBUwGDAVMBhAFTAYUBUQGGAVABiAFQAYoBUAGMAVABjgFRAZABUwGRAVIBkgFRAZMBTwGTAU4BkgFNAZEBTQGQAU0BjwFNAY4BTQGMAU0BiwFNAYoBTQGJAU0BhwFNAYYBTQGFAU0BgwFNAYIBTQGBAU0BgAFNAX8BTQF9AU0BfAFNAXsBTQF6AU0BeQFNAXgBTQF3AU0BdgFNAXUBTQF0AU0BcwFNAXIBTQFxAU0BcAFNAW8BTQFuAU0BbQFNAWwBTQFrAU0BaQFLAWgBSgFpAUoBawFKAW0BSgFvAUkBcAFJAXIBSAFzAUgBdQFIAXgBSAF6AUgBfAFIAX4BSAGAAUgBggFIAYQBSAGGAUgBiAFIAYoBSAGNAUgBjwFIAZEBSAGTAUgBlQFIAZcBSgGXAUwBlwFOAZgB",
    "trackTotal": "0",
    "transitCmd": "134",
    "virtualWall": "[]"
  },
  "version": "1.0"
}`

`2022-10-29 20:48:43.357 ERROR (MainThread) [custom_components.proscenic.vacuum_proscenic] Unknon error on refresh loop. Restart refresh loop.
Traceback (most recent call last):
  File "/config/custom_components/proscenic/vacuum_proscenic.py", line 202, in start_state_refresh_loop
    await asyncio.wait_for(self._wait_for_state_refresh(), timeout=60.0)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/config/custom_components/proscenic/vacuum_proscenic.py", line 309, in _wait_for_state_refresh
    self._map_received(values)
  File "/config/custom_components/proscenic/vacuum_proscenic.py", line 338, in _map_received
    map.map_svg = build_map(value['map'], value['track'])
  File "/config/custom_components/proscenic/vacuum_map_generator.py", line 48, in build_map
    placebyte(d[i + 1])
  File "/config/custom_components/proscenic/vacuum_map_generator.py", line 22, in placebyte
    full[((akt + 3) // 100)][((akt + 3) % 100)] = '0'
IndexError: list index out of range`

**Comment by albinmedoc** [comment]
Its the same for me

**Comment by albinmedoc** [comment]
As it says, list index out of range when we try to stuff into the variable full.
The full variable is a 2 dimensional array created like this: `full = [['.' for i in range(100)] for j in range(110)]`.
Where are the numbers 100 and 110 coming from? I interpret it as width and height on the map (height 100, width 110).

As we can see in the map response @goodbyepavlyi provided it includes two interesting keys `mapWidth` and `mapHeight`. They are both set to `700` in @goodbyepavlyi map response. For me they are set to `900`.

Maybe this are the values we should use when creating the `full` variable to handle the `list index out of range`-error.

This is just an idea and I have not tried it myself. 

@deblockt, are you still actively working on this integration?

**Comment by deblockt** [comment]
Hi, 

What is you vacuum model? 
I will try to look to provide a fixed for this issue.

@albinmedoc I sold my vacuum last week, so I will not be able to work on this integration :s

**Comment by goodbyepavlyi** [comment]
> Hi, 
> 
> 
> 
> What is you vacuum model? 
> 
> I will try to look to provide a fixed for this issue.
> 

Hey, it's a Sencor SRV 9250BK.

**Comment by deblockt** [comment]
This integration has only been tested with a proscenic 790T. All proscenic vacuum are not compatible with this integration.

**Comment by goodbyepavlyi** [comment]
So there is no way to get it supported?

**Comment by deblockt** [comment]
I just tried to set the size of "full" variable, but this doesn't work.
I think that the map is not stored on the "Sencor SRV 9250BK" as on the "proscenic 790T vacuum". 
I you want I can add a config to be able to disable the map entity to avoid extra issue. If it's working, you will be able to start/stop your vacuum using home assistant.

**Comment by goodbyepavlyi** [comment]
The config option could work since I don't know how to get the map working

**Comment by albinmedoc** [comment]
Actually my vacuum is from another brand called "Cleanmate" modell S995, it's popular in Sweden. 

I tried to make a library to control the vacuum before I encountered this integration. I found out that many request are the same. So I thought it was the "same" vacuum just white-branded. When I look up your cleaners they look almost identical, same with the app. 

I have made a [Home Assistant integration ](https://github.com/albinmedoc/ha-cleanmate) and previously a [HomeBridge plugin](https://github.com/albinmedoc/homebridge-cleanmate), but I can't manage to build the map. 

@deblockt how did you figure it out?

**Comment by albinmedoc** [comment]
I think we can share our knowledge. I see that you are reading the message from the vacuum by reading all bytes in the socket buffer (and then wait for timeout?). I have managed to read from the tcp header how long the message is, and then only read the message, without waiting for a timeout. I'm also getting both the status- and map-response locally by sending a tcp-request directly to the vacuum. Just like you are sending the commands.

**Comment by deblockt** [comment]
Hi, 

I think that the same protocol is used for both vacuum.
Is my integration working for you vacuum ? (start/stop/go to base)?

On my side, I use a timeout waiting for socket response, because If I don't send a ping request to the vacuum, I'm disconnected. So I try to read on the socket, If after n seconds I have nothing to read, I send a ping request. 


To get the map locally, I tried to do that sending a command, but without success.

The code to convert Map base64 to svg have not be written by me, the code come from another proscenic project. There is a difference between your vacuum and mine. The Cleanmate S995 use a LIDAR but the 790T use a infrared, so the map is not stored in the same way.

If you need to adapt some information on my integration to work with your vacuum, you can provide a PR or explain what is not working.

**Comment by deblockt** [comment]
When your integration start, can you get the current vacuum state?

**Comment by deblockt** [comment]
When your integration start, can you get the current vacuum state?

**Comment by goodbyepavlyi** [comment]
Hey, all the controls for the vacuum work great I can stop, start, dock it.

**Comment by albinmedoc** [comment]
> To get the map locally, I tried to do that sending a command, but without success.

I found the command by looking at the network traffic, I managed to get the map response by using [this function](https://github.com/albinmedoc/ha-cleanmate/blob/master/custom_components/cleanmate/devices/vacuum.py#L70).

> When your integration start, can you get the current vacuum state?

Yes, I can just call [this function.](https://github.com/albinmedoc/ha-cleanmate/blob/master/custom_components/cleanmate/devices/vacuum.py#L52)

**Comment by albinmedoc** [comment]
> The Cleanmate S995 use a LIDAR but the 790T use a infrared, so the map is not stored in the same way.

That's probably the reason your function isn't working for me.

**Comment by acs-lux** [comment]
This looks interesting, is it the same way as you are accessing it via udp?

[https://github.com/oskarn97/fhem-Proscenic](https://github.com/oskarn97/fhem-Proscenic)

I get the status of my vacuum using your integration but cant control it. In the WS capture I noticed there is no IP and no Port for mine in the comms. Still works with the app but maybe its all via the cloud only. I was really hoping I could control it with your latest but still no joy.

I dont get a map generated either.

**Comment by albinmedoc** [comment]
> 

In my [cleanmate integration](https://github.com/albinmedoc/ha-cleanmate) I'm using UDP packets to have full local control. 

I have manages to get the data for the map but not visualized it.

**Comment by acs-lux** [comment]
I tried the cleanmate but it doesnt accept the Authcode so I cant set it up

**Comment by acs-lux** [comment]
Hi, I do get the status of my proscenic 790T but have this in the logs and no map is generated. I cant control the vacuum either. 

This error originated from a custom integration.

Logger: custom_components.proscenic.vacuum_proscenic
Source: custom_components/proscenic/vacuum_proscenic.py:273
Integration: proscenic-vacuum (documentation, issues)
First occurred: 6:06:39 AM (2 occurrences)
Last logged: 6:22:22 AM

decoding issue for message b'C\x00\x00\x00\x13\x00\xc8\x00\x00\x00\x00\x00\xe8\x03\x00\x00\xd0\x07\x00\x00{"msg":"exit succeed","result":0,"version":""}\n\x1f\x01\x00\x00\xfb\x00\xc8\x00\x01\x00\x00\x00K\x02\x00\x00\x00\x00\x00\x00{"control":{"authCode":"XXXXXXXXXX","broadcast":"0","targetId":"XXXXXXXXXXXXXX","targetType":"1"},"value":{"clearArea":"11","clearId":"168550545532b4e62d86c3ed","clearModule":"3","clearSign":"2023-05-31-08-15-48-2","clearTime":"545","noteCmd":"101"},"version":"1.0"}\n'
decoding issue for message b'\xf1\x00\x00\x00\xfb\x00\xc8\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00{"control":{"authCode":"XXXXXXXXXX","broadcast":"0","targetId":"XXXXXXXXXXXXXX","targetType":"1"},"value":{"errRecordId":"0eabc1b26b9d40b7bb2be9a1256c8aea","errorCode":"9","errorDesc":"","noteCmd":"100"},"version":"1.0"}\nR\x01\x00\x00\xfb\x00\xc8\x00\x00\x00\x00\x00\xd9\x03}\x00\x00\x00\x00\x00{"control":{"broadcast":"0","iotType":"1","targetId":"XXXXXXXXXXXXXX","targetType":"1"},"value":{"errRecordId":"0eabc1b26b9d40b7bb2be9a1256c8aea","errorCode":"9","iotType":"1","noteCmd":"109","pushMsg":"proscenic robotic 790T has problem","pushType":"102","userId":"XXXXXXXXXXXXXXXXXXXXXXXXXXXX"},"version":"1.0"}\n'
Traceback (most recent call last):
  File "/config/custom_components/proscenic/vacuum_proscenic.py", line 273, in _wait_data_from_cloud
    decoded_data = read_data[last_opening_brace_index:].decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfb in position 51: invalid start byte

Does this mean aything to you? Its all there is in the logs. Maybe I have a very old firmware version.

The vacuum had an error this morning and was sat in the middle of the room after a clean so thats nothing to do with your integration. If I can only have status and no map or control then I guess its better than nothing. Pitty though.
